sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2827_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2827_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2833_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2833_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2866_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2866_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2916_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2916_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2940_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2940_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2942_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2942_filtered_matrix_removecol0_cpm_rename_median.txt2942_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2958_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2958_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2991_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2991_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2992_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2992_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt
sh ~/RNASEQ/Tools/SINGLE_SAMPLE_GSEA/SingleSampleGSEA.sh 2998_filtered_matrix_removecol0_cpm_rename_median.txt Human-HGG.rnaseq Tiwari_Human_Clusters.gmt 2998_filtered_matrix_removecol0_cpm_rename_median_tiwari.txt

cat *tiwari.txt > combined_tiwari.txt
