
drppm -AppendExpressionColorAsMetaData NTRK_NesCre_GfapCreER_TSNE_quotations.txt ../ssGSEA/combined_tiwari_ssgsea_transpose_edit.txt Cluster1_ESC_UP 95 false NTRK_NesCre_GfapCreER_TSNE_quotations_Tiwari_Cluster1_ESC_UP_Color.txt
drppm -AppendExpressionColorAsMetaData NTRK_NesCre_GfapCreER_TSNE_quotations.txt ../ssGSEA/combined_tiwari_ssgsea_transpose_edit.txt Cluster2_aNPC_ESC_UP 95 false NTRK_NesCre_GfapCreER_TSNE_quotations_Tiwari_Cluster2_aNPC_ESC_UP_Color.txt
drppm -AppendExpressionColorAsMetaData NTRK_NesCre_GfapCreER_TSNE_quotations.txt ../ssGSEA/combined_tiwari_ssgsea_transpose_edit.txt Cluster3_aNPC 95 false NTRK_NesCre_GfapCreER_TSNE_quotations_Tiwari_Cluster3_aNPC_Color.txt
drppm -AppendExpressionColorAsMetaData NTRK_NesCre_GfapCreER_TSNE_quotations.txt ../ssGSEA/combined_tiwari_ssgsea_transpose_edit.txt Cluster4_eA 95 false NTRK_NesCre_GfapCreER_TSNE_quotations_Tiwari_Cluster4_eA_Color.txt
drppm -AppendExpressionColorAsMetaData NTRK_NesCre_GfapCreER_TSNE_quotations.txt ../ssGSEA/combined_tiwari_ssgsea_transpose_edit.txt Cluster5_IA 95 false NTRK_NesCre_GfapCreER_TSNE_quotations_Tiwari_Cluster5_IA_Color.txt
